### ISSUE TITLE
why cant i upload to my badge on web ui

### ISSUE THREAD

**Issue by NOOBPLAYER8115** [hackzone/cz20-badge#72]
this is the error code in inspect element Uncaught (in promise) DOMException: Failed to execute 'controlTransferIn' on 'USBDevice': A transfer error has occurred.
await (async)
(anonymous) @ webusb.js:399
webusb.js:44 Uncaught ReferenceError: Cannot access 'n' before initialization
    at w (webusb.js:44:77)
    at y (webusb.js:25:32)
    at webusb.js:393:13
w @ webusb.js:44
y @ webusb.js:25
(anonymous) @ webusb.js:393

**Comment by francisduvivier** [comment]
Fixed in https://github.com/hackzone/cz20-badge/commit/25bfb62a36e24a5caa5061a7dea457f7a99856f1
But for it to get deployed to https://webusb.hackz.one/ the following PR is needed and needs to work here in this repo:
https://github.com/hackzone/cz20-badge/pull/74

**Comment by francisduvivier** [comment]
@NOOBPLAYER8115 should be fixed now, could you recheck on your side?
